apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-store.yaml
  - external-secret.yaml

labels:
  - pairs:
      app: scalable-read-heavy-api
      managed-by: kustomize
    includeSelectors: false
