# This file tells Kustomize which Kubernetes resources to include
# Kustomize is a tool that helps manage Kubernetes configurations
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of all Kubernetes resource files to include in this base configuration
# These files define the basic structure of our application
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml

# Labels that will be automatically added to all resources
# Labels help organize and identify resources in Kubernetes
labels:
  - pairs:
      app: scalable-read-heavy-api
      managed-by: kustomize
    includeSelectors: false
